# Generated by Django 4.1.2 on 2022-10-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("roll_no", models.IntegerField(max_length=50)),
            ],
        ),
    ]
