# Generated by Django 4.1.2 on 2022-10-28 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("work_app", "0002_student"),
    ]

    operations = [
        migrations.RemoveField(model_name="student", name="roll_no",),
    ]
