# Generated by Django 4.1.2 on 2022-10-28 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("work_app", "0003_remove_student_roll_no"),
    ]

    operations = [
        migrations.RenameModel(old_name="Student", new_name="Stud",),
    ]
