# Generated by Django 4.1.2 on 2022-10-28 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("work_app", "0004_rename_student_stud"),
    ]

    operations = [
        migrations.DeleteModel(name="Stud",),
    ]
