# Generated by Django 4.1.2 on 2022-10-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_app", "0005_delete_stud"),
    ]

    operations = [
        migrations.CreateModel(
            name="Studnt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
    ]
