# Generated by Django 4.1.2 on 2022-11-02 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("work_app", "0007_student_delete_studnt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student", name="roll_no", field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name="mark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll_no", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="work_app.student",
                    ),
                ),
            ],
        ),
    ]
