# Generated by Django 4.1.2 on 2022-11-02 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("work_app", "0008_alter_student_roll_no_mark"),
    ]

    operations = [
        migrations.RemoveField(model_name="mark", name="user",),
    ]
