# Generated by Django 4.1.2 on 2022-11-02 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("work_app", "0009_remove_mark_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="mark",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="work_app.student",
            ),
        ),
    ]
