# Generated by Django 4.1.2 on 2022-11-08 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("work_app", "0010_mark_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workrequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("vehicle_model", models.CharField(max_length=20)),
                ("problem", models.CharField(max_length=20)),
                ("location", models.CharField(max_length=40)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("phone_number", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=20)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workshop",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
